name: "Bug Report 🐛"
description: Report a bug or crash found in the mod.
title: "[BUG] <Short summary>"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping polish the Odyssey! Please fill out the details below.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened and what were you doing?
      placeholder: e.g. The game crashed when activating Joker X with hand Y.
    validations:
      required: true
  - type: textarea
    id: log
    attributes:
      label: Ghost.log Content
      description: "Please copy and paste the content of your Ghost.log file here (found in your game save folder). This is essential for debugging."
      render: lua
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Mod Version
      placeholder: e.g. Alpha 0.1.0
